spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
#    driverClassName: com.mysql.jdbc.Driver
#    tomcat:
#      max-wait: 10000
#      max-active: 5
#      max-idle: 2
#      min-idle: 1
    
#hibernate:
#  dialect: org.hibernate.dialect.MySQL5Dialect
#  ddl-auto: create-drop
##none, validate, update or create-drop
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  queries:
    users-query: select username, password, true as enabled from user where username=? and status='A'
    roles-query: select u.username, r.role from user u inner join user_role ur on(u.id=ur.userid) inner join role r on(ur.roleid=r.id) where u.username=?

  mvc: 
    view:
      prefix: /
      suffix: .jsp
  thymeleaf:
      prefix: /
      suffix: .jsp
#  security: 
#    user:
#      name: admin
#      password: 123
      
logging:
  level:
    root: WARN
    org:
      springframework: DEBUG
    com:
      springboot: INFO    
      
  file: web.log

server:
  port: 8080